package timber

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

type zshCommandOptions struct {
	runtime Runtime
	name    string
	out     string
	force   bool
}

type generatedZshFile struct {
	kind  string
	path  string
	write func(string) error
}

func NewZshCommand(runtime Runtime) *cobra.Command {
	options := &zshCommandOptions{runtime: runtime}

	command := &cobra.Command{
		Use:   `zsh`,
		Short: `Generate zsh wrapper, completion, and autoload helper for timber`,
		Args:  cobra.NoArgs,
		RunE:  options.Execute,
	}

	command.Flags().StringVarP(&options.name, `name`, `n`, `t`, `name of generated zsh function`)
	command.Flags().StringVarP(&options.out, `out`, `o`, runtime.xdgDataHome()+`/zsh/site-functions`, `output directory for generated files`)
	command.Flags().BoolVarP(&options.force, `force`, `f`, false, `overwrite existing generated files`)

	return command
}

func (x *zshCommandOptions) Execute(command *cobra.Command, args []string) error {
	if err := os.MkdirAll(x.out, 0o755); err != nil {
		return fmt.Errorf(`create output directory: %w`, err)
	}

	generatedFiles := x.generatedFiles()
	if !x.force {
		if err := ensureGeneratedFilesDoNotExist(generatedFiles); err != nil {
			return err
		}
	}

	for _, generatedFile := range generatedFiles {
		if err := generatedFile.write(generatedFile.path); err != nil {
			return err
		}
	}

	return x.reportGeneratedFiles(command.ErrOrStderr(), generatedFiles)
}

func (x *zshCommandOptions) reportGeneratedFiles(output io.Writer, generatedFiles []generatedZshFile) error {
	for _, generatedFile := range generatedFiles {
		if _, err := fmt.Fprintf(output, "Wrote %s\n", generatedFile.path); err != nil {
			return fmt.Errorf("report generated file: %w", err)
		}
	}
	if _, err := fmt.Fprintf(output, "Ensure %s is on fpath. Restart zsh or run compinit if completion does not appear immediately.\n", x.out); err != nil {
		return fmt.Errorf("report fpath instructions: %w", err)
	}

	return nil
}

func (x *zshCommandOptions) generatedFiles() []generatedZshFile {
	return []generatedZshFile{
		{kind: "function", path: filepath.Join(x.out, x.name), write: x.writeFunctionFile},
		{kind: "completion", path: filepath.Join(x.out, `_`+x.name), write: x.writeCompletionFile},
		{kind: "autoload helper", path: filepath.Join(x.out, `_`+x.name+`_autoload`), write: x.writeAutoloadFile},
	}
}

func ensureGeneratedFilesDoNotExist(generatedFiles []generatedZshFile) error {
	for _, generatedFile := range generatedFiles {
		if _, err := os.Stat(generatedFile.path); err == nil {
			return fmt.Errorf(`%s file %q already exists; use --force to overwrite`, generatedFile.kind, generatedFile.path)
		}
	}

	return nil
}

func (x *zshCommandOptions) writeFunctionFile(target string) error {
	content := `# Generated by timber generate zsh
# DO NOT EDIT. Regenerate with timber generate zsh

` + x.name + `() {
    case "$1" in
    create)
        shift
        local no_cd=0 herdr=0 no_herdr=0 skip_next=0
        local -a forward=()
        local arg
        for arg in "$@"; do
            if (( skip_next )); then
                forward+=("$arg")
                skip_next=0
                continue
            fi
            case "$arg" in
            --no-cd)
                no_cd=1
                ;;
            --herdr)
                herdr=1
                forward+=("$arg")
                ;;
            --no-herdr)
                no_herdr=1
                forward+=("$arg")
                ;;
            -u|--upstream)
                forward+=("$arg")
                skip_next=1
                ;;
            --upstream=*)
                forward+=("$arg")
                ;;
            -*)
                forward+=("$arg")
                ;;
            *)
                forward+=("$arg")
                ;;
            esac
        done
        # Write the created path to a temp file so timber keeps a real TTY for
        # interactive prompts (repo picker / name input). Capturing stdout would
        # blank the bubbletea UI.
        local path_file
        path_file=$(mktemp) || return $?
        TIMBER_CREATE_PATH_FILE=$path_file command timber create "${forward[@]}"
        local create_status=$?
        local target_dir=""
        if [[ -s "$path_file" ]]; then
            target_dir=$(<"$path_file")
        fi
        rm -f "$path_file"
        if (( create_status != 0 )); then
            return $create_status
        fi
        if (( no_cd || herdr || ( ${HERDR_ENV:-0} == 1 && ! no_herdr ) )); then
            return 0
        fi
        if [[ -z "$target_dir" ]]; then
            echo "Created worktree path not reported" >&2
            return 1
        fi
        if ! [[ -d "$target_dir" ]]; then
            echo "Worktree not found at $target_dir" >&2
            return 1
        fi
        cd "$target_dir"
        ;;
    switch|sw)
        shift
        local path_file
        path_file=$(mktemp) || return $?
        TIMBER_SWITCH_PATH_FILE=$path_file command timber switch "$@"
        local switch_status=$?
        local target_dir=""
        if [[ -s "$path_file" ]]; then
            target_dir=$(<"$path_file")
        fi
        rm -f "$path_file"
        if (( switch_status != 0 )); then
            return $switch_status
        fi
        if [[ -z "$target_dir" ]]; then
            return 0
        fi
        if ! [[ -d "$target_dir" ]]; then
            echo "Worktree not found at $target_dir" >&2
            return 1
        fi
        cd "$target_dir"
        ;;
    repo)
        case "$2" in
        rename|mv)
            local path_file
            path_file=$(mktemp) || return $?
            TIMBER_RENAME_PATH_FILE=$path_file command timber "$@"
            local rename_status=$?
            local target_dir=""
            if [[ -s "$path_file" ]]; then
                target_dir=$(<"$path_file")
            fi
            rm -f "$path_file"
            if (( rename_status != 0 )); then
                return $rename_status
            fi
            if [[ -n "$target_dir" ]]; then
                if ! [[ -d "$target_dir" ]]; then
                    echo "Renamed worktree not found at $target_dir" >&2
                    return 1
                fi
                cd "$target_dir" || return $?
            fi
            ;;
        import)
            # Snapshot cwd, then leave it before the source tree may disappear;
            # import moves the source worktrees to the system trash.
            local previous_dir=$PWD
            cd "$HOME" || return $?
            local command_status
            (
                cd "$previous_dir" || exit $?
                command timber "$@"
            )
            command_status=$?
            if (( command_status != 0 )); then
                # A failed command did not remove the original directory, so leave
                # the caller where they started rather than stranded in $HOME.
                cd "$previous_dir" 2>/dev/null || return $command_status
                return $command_status
            fi
            cd "$HOME"
            ;;
        *)
            command timber "$@"
            return $?
            ;;
        esac
        ;;
    remove|rm)
        # Snapshot cwd, then leave it before remove deletes the current worktree.
        local previous_dir=$PWD
        cd "$HOME" || return $?
        local command_status
        (
            cd "$previous_dir" || exit $?
            command timber "$@"
        )
        command_status=$?
        if (( command_status != 0 )); then
            # A failed command did not remove the original directory, so leave
            # the caller where they started rather than stranded in $HOME.
            cd "$previous_dir" 2>/dev/null || return $command_status
            return $command_status
        fi
        cd "$HOME"
        ;;
    *)
        command timber "$@"
        ;;
    esac
}
`

	return os.WriteFile(target, []byte(content), 0o644)
}

func (x *zshCommandOptions) writeAutoloadFile(target string) error {
	content := `#autoload ` + x.name + `

# Generated by timber generate zsh
# DO NOT EDIT. Regenerate with timber generate zsh
`

	return os.WriteFile(target, []byte(content), 0o644)
}

func (x *zshCommandOptions) writeCompletionFile(target string) error {
	content := `#compdef ` + x.name + `

# Generated by timber generate zsh
# DO NOT EDIT. Regenerate with timber generate zsh

_` + x.name + `() {
    local context state state_descr line
    typeset -A opt_args

    local -a subcommands
    subcommands=(
        'create:Create a managed Git worktree'
        'list:List managed Git worktrees'
        'ls:List managed Git worktrees'
        'prune:Remove clean merged managed worktrees'
        'clean:Remove clean merged managed worktrees'
        'remove:Remove a managed Git worktree'
        'rm:Remove a managed Git worktree'
        'repo:Manage registered repositories'
        'herdr:Manage the Herdr plugin and spaces'
        'generate:Generate shell integration'
        'switch:Switch to a worktree'
        'tui:Interactively create a worktree or open an existing one'
    )

    if (( CURRENT == 2 )); then
        _describe 'command' subcommands
        return
    fi

    case $words[2] in
    create)
        shift words
        (( CURRENT-- ))
        _arguments -M 'r:|=*' \
            '--no-cd[Create without changing directories]' \
            '(--no-herdr)--herdr[Also create a Herdr workspace for the new worktree]' \
            '(--herdr)--no-herdr[Do not create a Herdr workspace]' \
            '(-u --upstream)'{-u,--upstream}'[Upstream branch]:upstream branch:' \
            '(-h --help)'{-h,--help}'[help for create]' \
            '1:worktree name:->create_name'
        ;;
    list|ls)
        shift words
        (( CURRENT-- ))
        _arguments \
            '(-h --help)'{-h,--help}'[help for list]' \
            '1:repository:->repo_qualifiers'
        ;;
    switch|sw)
        shift words
        (( CURRENT-- ))
        _arguments -M 'r:|=*' \
            {-c,--create}'[Create the worktree if it does not exist]' \
            '--no-cd[Create without changing directories]' \
            '(--no-herdr)--herdr[Also create a Herdr workspace for the new worktree]' \
            '(--herdr)--no-herdr[Do not create a Herdr workspace]' \
            '(-u --upstream)'{-u,--upstream}'[Upstream branch]:upstream branch:' \
            '1:worktree name:->switch_name'
        ;;
    remove|rm)
        shift words
        (( CURRENT-- ))
        _arguments \
            '1:worktree name:->worktrees'
        ;;
    herdr)
        local -a herdr_commands
        herdr_commands=(
            'install:Install the Herdr plugin and print keybinding instructions'
            'space:Set up a Herdr space for a managed Git worktree'
        )
        if (( CURRENT == 3 )); then
            _describe 'herdr command' herdr_commands
            return
        fi
        case $words[3] in
        install)
            shift words
            (( CURRENT-- ))
            shift words
            (( CURRENT-- ))
            _arguments \
                '(-h --help)'{-h,--help}'[help for install]'
            ;;
        space)
            shift words
            (( CURRENT-- ))
            shift words
            (( CURRENT-- ))
            _arguments \
                '(-n --new)'{-n,--new}'[Open a new Herdr workspace]' \
                '1:worktree name:->worktrees'
            ;;
        esac
        ;;
    prune|clean)
        shift words
        (( CURRENT-- ))
        _arguments \
            '(-p --prompt)'{-p,--prompt}'[Prompt before pruning]' \
            '(-n --dry-run)'{-n,--dry-run}'[List worktrees that would be pruned]' \
            '(-h --help)'{-h,--help}'[help for prune]' \
            '1:repository:->repo_qualifiers'
        ;;
    tui)
        shift words
        (( CURRENT-- ))
        _arguments \
            '(--no-herdr)--herdr[Also create a Herdr workspace for a new worktree]' \
            '(--herdr)--no-herdr[Do not create a Herdr workspace]' \
            '(-h --help)'{-h,--help}'[help for tui]'
        ;;
    repo)
        local -a repo_commands
        repo_commands=(
            'add:Register a bare repository'
            'import:Convert an existing clone into a managed Timber repository'
            'list:List registered repositories'
            'ls:List registered repositories'
            'remove:Remove a registered repository'
            'rm:Remove a registered repository'
            'rename:Rename a registered repository'
            'mv:Rename a registered repository'
        )
        if (( CURRENT == 3 )); then
            _describe 'repo command' repo_commands
            return
        fi
        case $words[3] in
        list|ls)
            shift words
            (( CURRENT-- ))
            shift words
            (( CURRENT-- ))
            _arguments \
                '(-q --quiet)'{-q,--quiet}'[Print repository names only]' \
                '(-h --help)'{-h,--help}'[help for list]'
            ;;
        import)
            shift words
            (( CURRENT-- ))
            shift words
            (( CURRENT-- ))
            _arguments \
                '(-n --name)'{-n,--name}'[Repository name]:repository name:' \
                '(-h --help)'{-h,--help}'[help for import]' \
                '1:source path:_files -/'
            ;;
        remove|rm)
            state=repos
            ;;
        rename|mv)
            if (( CURRENT == 4 )); then
                state=repos
            elif (( CURRENT == 5 )); then
                _message 'new repository name'
                return
            fi
            ;;
        esac
        ;;
    esac

    case $state in
    switch_name)
        if (( ${words[(I)-c]} || ${words[(I)--create]} )); then
            state=create_name
        else
            state=worktrees
        fi
        ;;
    esac

    local data_home=${XDG_DATA_HOME:-$HOME/.local/share}
    local worktree_root=${TIMBER_WORKTREE_ROOT:-$HOME/worktrees}

    case $state in
    repos)
        local -a repos
        local repo_dir repo_name
        for repo_dir in "$data_home"/timber/repos/*.git(N/); do
            repos+=("${repo_dir:t:r}")
        done
        _describe 'repositories' repos
        ;;
    repo_qualifiers|create_name)
        local -a qualifiers
        local repo_dir repo_name name="" repo_prefix=""
        if [[ $PREFIX == *@* ]]; then
            name=${PREFIX%@*}
            repo_prefix=${PREFIX##*@}
        elif [[ -n $PREFIX ]]; then
            if [[ $state == create_name ]]; then
                _message 'worktree name'
            fi
            return 0
        fi
        for repo_dir in "$data_home"/timber/repos/*.git(N/); do
            repo_name=${repo_dir:t:r}
            [[ $repo_name == ${repo_prefix}* ]] || continue
            qualifiers+=("${name}@$repo_name")
        done
        (( $#qualifiers )) && compadd -S '' -- "${qualifiers[@]}"
        ;;
    worktrees)
        local -a completions
        local repo_dir repo_name worktree_dir parent name
        if [[ $PREFIX == *@* ]]; then
            local worktree_name=${PREFIX%@*}
            local repo_prefix=${PREFIX##*@}
            [[ -n $worktree_name ]] || return 0
            for repo_dir in "$data_home"/timber/repos/*.git(N/); do
                repo_name=${repo_dir:t:r}
                [[ $repo_name == ${repo_prefix}* ]] || continue
                [[ -e "$worktree_root/$repo_name/$worktree_name/$repo_name/.git" ]] || continue
                completions+=("$worktree_name@$repo_name")
            done
            (( $#completions )) && compadd -Q -- "${completions[@]}"
            return 0
        fi
        local -A name_count
        local -A name_repos
        for repo_dir in "$data_home"/timber/repos/*.git(N/); do
            repo_name=${repo_dir:t:r}
            for worktree_dir in "$worktree_root/$repo_name"/**/"$repo_name"(N/); do
                [[ -e "$worktree_dir/.git" ]] || continue
                parent=${worktree_dir:h}
                name=${parent#$worktree_root/$repo_name/}
                if [[ -n "$name" && "$name" != "$parent" ]]; then
                    name_count[$name]=$(( ${name_count[$name]:-0} + 1 ))
                    name_repos[$name]+="$repo_name "
                fi
            done
        done
        local repo
        for name in ${(k)name_count}; do
            if [[ ${name_count[$name]} -eq 1 ]]; then
                completions+=("$name")
            else
                for repo in ${(z)name_repos[$name]}; do
                    completions+=("$name@$repo")
                done
            fi
        done
        (( $#completions )) && compadd -Q -- "${completions[@]}"
        return 0
        ;;
    esac
}
`

	return os.WriteFile(target, []byte(content), 0o644)
}
