package timber

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

type zshCommandOptions struct {
	runtime Runtime
	name    string
	out     string
	force   bool
}

type generatedZshFile struct {
	kind  string
	path  string
	write func(string) error
}

func NewZshCommand(runtime Runtime) *cobra.Command {
	options := &zshCommandOptions{runtime: runtime}

	command := &cobra.Command{
		Use:   `zsh`,
		Short: `Generate zsh wrapper, completion, and autoload helper for timber`,
		Args:  cobra.NoArgs,
		RunE:  options.Execute,
	}

	command.Flags().StringVarP(&options.name, `name`, `n`, `t`, `name of generated zsh function`)
	command.Flags().StringVarP(&options.out, `out`, `o`, runtime.xdgDataHome()+`/zsh/site-functions`, `output directory for generated files`)
	command.Flags().BoolVarP(&options.force, `force`, `f`, false, `overwrite existing generated files`)

	return command
}

func (x *zshCommandOptions) Execute(command *cobra.Command, args []string) error {
	if err := os.MkdirAll(x.out, 0o755); err != nil {
		return fmt.Errorf(`create output directory: %w`, err)
	}

	generatedFiles := x.generatedFiles()
	if !x.force {
		if err := ensureGeneratedFilesDoNotExist(generatedFiles); err != nil {
			return err
		}
	}

	for _, generatedFile := range generatedFiles {
		if err := generatedFile.write(generatedFile.path); err != nil {
			return err
		}
	}

	return x.reportGeneratedFiles(command.ErrOrStderr(), generatedFiles)
}

func (x *zshCommandOptions) reportGeneratedFiles(output io.Writer, generatedFiles []generatedZshFile) error {
	for _, generatedFile := range generatedFiles {
		if _, err := fmt.Fprintf(output, "Wrote %s\n", generatedFile.path); err != nil {
			return fmt.Errorf("report generated file: %w", err)
		}
	}
	if _, err := fmt.Fprintf(output, "Ensure %s is on fpath. Restart zsh or run compinit if completion does not appear immediately.\n", x.out); err != nil {
		return fmt.Errorf("report fpath instructions: %w", err)
	}

	return nil
}

func (x *zshCommandOptions) generatedFiles() []generatedZshFile {
	return []generatedZshFile{
		{kind: "function", path: filepath.Join(x.out, x.name), write: x.writeFunctionFile},
		{kind: "completion", path: filepath.Join(x.out, `_`+x.name), write: x.writeCompletionFile},
		{kind: "autoload helper", path: filepath.Join(x.out, `_`+x.name+`_autoload`), write: x.writeAutoloadFile},
	}
}

func ensureGeneratedFilesDoNotExist(generatedFiles []generatedZshFile) error {
	for _, generatedFile := range generatedFiles {
		if _, err := os.Stat(generatedFile.path); err == nil {
			return fmt.Errorf(`%s file %q already exists; use --force to overwrite`, generatedFile.kind, generatedFile.path)
		}
	}

	return nil
}

func (x *zshCommandOptions) writeFunctionFile(target string) error {
	content := `# Generated by timber generate zsh
# DO NOT EDIT. Regenerate with timber generate zsh

` + x.name + `() {
    case "$1" in
    create)
        shift
        local no_cd=0 herdr=0 no_herdr=0 skip_next=0
        local -a forward=()
        local arg
        for arg in "$@"; do
            if (( skip_next )); then
                forward+=("$arg")
                skip_next=0
                continue
            fi
            case "$arg" in
            --no-cd)
                no_cd=1
                ;;
            --herdr)
                herdr=1
                forward+=("$arg")
                ;;
            --no-herdr)
                no_herdr=1
                forward+=("$arg")
                ;;
            -u|--upstream)
                forward+=("$arg")
                skip_next=1
                ;;
            --upstream=*)
                forward+=("$arg")
                ;;
            -*)
                forward+=("$arg")
                ;;
            *)
                forward+=("$arg")
                ;;
            esac
        done
        # Write the created path to a temp file so timber keeps a real TTY for
        # interactive prompts (repo picker / name input). Capturing stdout would
        # blank the bubbletea UI.
        local path_file
        path_file=$(mktemp) || return $?
        TIMBER_CREATE_PATH_FILE=$path_file command timber create "${forward[@]}"
        local create_status=$?
        local target_dir=""
        if [[ -s "$path_file" ]]; then
            target_dir=$(<"$path_file")
        fi
        rm -f "$path_file"
        if (( create_status != 0 )); then
            return $create_status
        fi
        if (( no_cd || herdr || ( ${HERDR_ENV:-0} == 1 && ! no_herdr ) )); then
            return 0
        fi
        if [[ -z "$target_dir" ]]; then
            echo "Created worktree path not reported" >&2
            return 1
        fi
        if ! [[ -d "$target_dir" ]]; then
            echo "Worktree not found at $target_dir" >&2
            return 1
        fi
        cd "$target_dir"
        ;;
    switch|sw)
        shift
        local path_file
        path_file=$(mktemp) || return $?
        TIMBER_SWITCH_PATH_FILE=$path_file command timber switch "$@"
        local switch_status=$?
        local target_dir=""
        if [[ -s "$path_file" ]]; then
            target_dir=$(<"$path_file")
        fi
        rm -f "$path_file"
        if (( switch_status != 0 )); then
            return $switch_status
        fi
        if [[ -z "$target_dir" ]]; then
            return 0
        fi
        if ! [[ -d "$target_dir" ]]; then
            echo "Worktree not found at $target_dir" >&2
            return 1
        fi
        cd "$target_dir"
        ;;
    repo)
        case "$2" in
        rename|mv)
            local path_file
            path_file=$(mktemp) || return $?
            TIMBER_RENAME_PATH_FILE=$path_file command timber "$@"
            local rename_status=$?
            local target_dir=""
            if [[ -s "$path_file" ]]; then
                target_dir=$(<"$path_file")
            fi
            rm -f "$path_file"
            if (( rename_status != 0 )); then
                return $rename_status
            fi
            if [[ -n "$target_dir" ]]; then
                if ! [[ -d "$target_dir" ]]; then
                    echo "Renamed worktree not found at $target_dir" >&2
                    return 1
                fi
                cd "$target_dir" || return $?
            fi
            ;;
        import)
            # Snapshot cwd, then leave it before the source tree may disappear;
            # import moves the source worktrees to the system trash.
            local previous_dir=$PWD
            cd "$HOME" || return $?
            local command_status
            (
                cd "$previous_dir" || exit $?
                command timber "$@"
            )
            command_status=$?
            if (( command_status != 0 )); then
                # A failed command did not remove the original directory, so leave
                # the caller where they started rather than stranded in $HOME.
                cd "$previous_dir" 2>/dev/null || return $command_status
                return $command_status
            fi
            cd "$HOME"
            ;;
        *)
            command timber "$@"
            return $?
            ;;
        esac
        ;;
    remove|rm)
        # Snapshot cwd, then leave it before remove deletes the current worktree.
        local previous_dir=$PWD
        cd "$HOME" || return $?
        local command_status
        (
            cd "$previous_dir" || exit $?
            command timber "$@"
        )
        command_status=$?
        if (( command_status != 0 )); then
            # A failed command did not remove the original directory, so leave
            # the caller where they started rather than stranded in $HOME.
            cd "$previous_dir" 2>/dev/null || return $command_status
            return $command_status
        fi
        cd "$HOME"
        ;;
    *)
        command timber "$@"
        ;;
    esac
}
`

	return os.WriteFile(target, []byte(content), 0o644)
}

func (x *zshCommandOptions) writeAutoloadFile(target string) error {
	content := `#autoload ` + x.name + `

# Generated by timber generate zsh
# DO NOT EDIT. Regenerate with timber generate zsh
`

	return os.WriteFile(target, []byte(content), 0o644)
}

func (x *zshCommandOptions) writeCompletionFile(target string) error {
	// Completion delegates to 'timber __complete', so flags, subcommands,
	// and argument completions never drift from the Cobra definitions.
	// Only wrapper-only flags are layered on top.
	content := fmt.Sprintf(`#compdef %[1]s
compdef _%[1]s %[1]s

# Generated by timber generate zsh
# DO NOT EDIT. Regenerate with timber generate zsh

__%[1]s_debug()
{
    local file="$BASH_COMP_DEBUG_FILE"
    if [[ -n ${file} ]]; then
        echo "$*" >> "${file}"
    fi
}

_%[1]s()
{
    local shellCompDirectiveError=%[3]d
    local shellCompDirectiveNoSpace=%[4]d
    local shellCompDirectiveNoFileComp=%[5]d
    local shellCompDirectiveFilterFileExt=%[6]d
    local shellCompDirectiveFilterDirs=%[7]d
    local shellCompDirectiveKeepOrder=%[8]d

    local lastParam lastChar flagPrefix requestComp out directive comp lastComp noSpace keepOrder
    local -a completions

    __%[1]s_debug "\n========= starting completion logic =========="
    __%[1]s_debug "CURRENT: ${CURRENT}, words[*]: ${words[*]}"

    # The user could have moved the cursor backwards on the command-line.
    # We need to trigger completion from the $CURRENT location, so we need
    # to truncate the command-line ($words) up to the $CURRENT location.
    # (We cannot use $CURSOR as its value does not work when a command is an alias.)
    words=("${=words[1,CURRENT]}")
    __%[1]s_debug "Truncated words[*]: ${words[*]},"

    lastParam=${words[-1]}
    lastChar=${lastParam[-1]}
    __%[1]s_debug "lastParam: ${lastParam}, lastChar: ${lastChar}"

    # For zsh, when completing a flag with an = (e.g., %[1]s -n=<TAB>)
    # completions must be prefixed with the flag
    setopt local_options BASH_REMATCH
    if [[ "${lastParam}" =~ '-.*=' ]]; then
        # We are dealing with a flag with an =
        flagPrefix="-P ${BASH_REMATCH}"
    fi

    # Prepare the command to obtain completions.
    # %[1]s is a shell wrapper, so always call through to the timber binary
    # instead of recursing into the wrapper.
    requestComp="command timber %[2]s ${words[2,-1]}"
    if [ "${lastChar}" = "" ]; then
        # If the last parameter is complete (there is a space following it)
        # We add an extra empty parameter so we can indicate this to the go completion code.
        __%[1]s_debug "Adding extra empty parameter"
        requestComp="${requestComp} \"\""
    fi

    __%[1]s_debug "About to call: eval ${requestComp}"

    # Use eval to handle any environment variables and such
    out=$(eval ${requestComp} 2>/dev/null)
    __%[1]s_debug "completion output: ${out}"

    # Extract the directive integer following a : from the last line
    local lastLine
    while IFS='\n' read -r line; do
        lastLine=${line}
    done < <(printf "%%s\n" "${out[@]}")
    __%[1]s_debug "last line: ${lastLine}"

    if [ "${lastLine[1]}" = : ]; then
        directive=${lastLine[2,-1]}
        # Remove the directive including the : and the newline
        local suffix
        (( suffix=${#lastLine}+2))
        out=${out[1,-$suffix]}
    else
        # There is no directive specified.  Leave $out as is.
        __%[1]s_debug "No directive found.  Setting do default"
        directive=0
    fi

    __%[1]s_debug "directive: ${directive}"
    __%[1]s_debug "completions: ${out}"
    __%[1]s_debug "flagPrefix: ${flagPrefix}"

    if [ $((directive & shellCompDirectiveError)) -ne 0 ]; then
        __%[1]s_debug "Completion received error. Ignoring completions."
        return
    fi

    local activeHelpMarker="%[9]s"
    local endIndex=${#activeHelpMarker}
    local startIndex=$((${#activeHelpMarker}+1))
    local hasActiveHelp=0
    while IFS='\n' read -r comp; do
        # Check if this is an activeHelp statement (i.e., prefixed with $activeHelpMarker)
        if [ "${comp[1,$endIndex]}" = "$activeHelpMarker" ];then
            __%[1]s_debug "ActiveHelp found: $comp"
            comp="${comp[$startIndex,-1]}"
            if [ -n "$comp" ]; then
                compadd -x "${comp}"
                __%[1]s_debug "ActiveHelp will need delimiter"
                hasActiveHelp=1
            fi

            continue
        fi

        if [ -n "$comp" ]; then
            # If requested, completions are returned with a description.
            # The description is preceded by a TAB character.
            # For zsh's _describe, we need to use a : instead of a TAB.
            # We first need to escape any : as part of the completion itself.
            comp=${comp//:/\\:}

            local tab="$(printf '\t')"
            comp=${comp//$tab/:}

            __%[1]s_debug "Adding completion: ${comp}"
            completions+=${comp}
            lastComp=$comp
        fi
    done < <(printf "%%s\n" "${out[@]}")

    # The shell wrapper adds 'create --no-cd', which timber itself does not
    # define, so offer it alongside Cobra's completions when completing flags.
    if [[ ${words[2]} == create && ${lastParam} == -* ]]; then
        if (( ${completions[(I)--no-cd:*]:-0} == 0 )); then
            completions+=('--no-cd:Create without changing directories')
        fi
    fi

    # Add a delimiter after the activeHelp statements, but only if:
    # - there are completions following the activeHelp statements, or
    # - file completion will be performed (so there will be choices after the activeHelp)
    if [ $hasActiveHelp -eq 1 ]; then
        if [ ${#completions} -ne 0 ] || [ $((directive & shellCompDirectiveNoFileComp)) -eq 0 ]; then
            __%[1]s_debug "Adding activeHelp delimiter"
            compadd -x "--"
            hasActiveHelp=0
        fi
    fi

    if [ $((directive & shellCompDirectiveNoSpace)) -ne 0 ]; then
        __%[1]s_debug "Activating nospace."
        noSpace="-S ''"
    fi

    if [ $((directive & shellCompDirectiveKeepOrder)) -ne 0 ]; then
        __%[1]s_debug "Activating keep order."
        keepOrder="-V"
    fi

    if [ $((directive & shellCompDirectiveFilterFileExt)) -ne 0 ]; then
        # File extension filtering
        local filteringCmd
        filteringCmd='_files'
        for filter in ${completions[@]}; do
            if [ ${filter[1]} != '*' ]; then
                # zsh requires a glob pattern to do file filtering
                filter="\*.$filter"
            fi
            filteringCmd+=" -g $filter"
        done
        filteringCmd+=" ${flagPrefix}"

        __%[1]s_debug "File filtering command: $filteringCmd"
        _arguments '*:filename:'"$filteringCmd"
    elif [ $((directive & shellCompDirectiveFilterDirs)) -ne 0 ]; then
        # File completion for directories only
        local subdir
        subdir="${completions[1]}"
        if [ -n "$subdir" ]; then
            __%[1]s_debug "Listing directories in $subdir"
            pushd "${subdir}" >/dev/null 2>&1
        else
            __%[1]s_debug "Listing directories in ."
        fi

        local result
        _arguments '*:dirname:_files -/'" ${flagPrefix}"
        result=$?
        if [ -n "$subdir" ]; then
            popd >/dev/null 2>&1
        fi
        return $result
    else
        __%[1]s_debug "Calling _describe"
        if eval _describe $keepOrder "completions" completions $flagPrefix $noSpace; then
            __%[1]s_debug "_describe found some completions"

            # Return the success of having called _describe
            return 0
        else
            __%[1]s_debug "_describe did not find completions."
            __%[1]s_debug "Checking if we should do file completion."
            if [ $((directive & shellCompDirectiveNoFileComp)) -ne 0 ]; then
                __%[1]s_debug "deactivating file completion"

                # We must return an error code here to let zsh know that there were no
                # completions found by _describe; this is what will trigger other
                # matching algorithms to attempt to find completions.
                # For example zsh can match letters in the middle of words.
                return 1
            else
                # Perform file completion
                __%[1]s_debug "Activating file completion"

                # We must return the result of this command, so it must be the
                # last command, or else we must store its result to return it.
                _arguments '*:filename:_files'" ${flagPrefix}"
            fi
        fi
    fi
}

# don't run the completion function when being source-ed or eval-ed
if [ "$funcstack[1]" = "_%[1]s" ]; then
    _%[1]s
fi
`, x.name, cobra.ShellCompRequestCmd,
		cobra.ShellCompDirectiveError, cobra.ShellCompDirectiveNoSpace, cobra.ShellCompDirectiveNoFileComp,
		cobra.ShellCompDirectiveFilterFileExt, cobra.ShellCompDirectiveFilterDirs, cobra.ShellCompDirectiveKeepOrder,
		"_activeHelp_ ")

	return os.WriteFile(target, []byte(content), 0o644)
}
